name: Daily Python Script

on:
  schedule:
    - cron: "30 7 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decode Credentials File
        run: echo "${{ secrets.CREDENTIAL }}" | base64 --decode > credential.json

      - name: Run script
        env:
          CREDENTIAL: ${{ secrets.CREDENTIAL }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
        run: python main.py
